---
- name: 'Gather facts'
  hosts: 'all'
  gather_facts: true
  become: true

- name: 'Postgresql snippet'
  hosts: 'postgresql-client'
  gather_facts: true
  become: true

  tasks:

    - name: 'Prepare snippet with Postgres commands for vagrant user'
      ansible.builtin.template:
        src: 'postgresql_snippet.txt.j2'
        dest: '/home/vagrant/postgresql_snippet.txt'
        owner: 'vagrant'
        group: 'vagrant'
        mode: '0644'

    - name: 'Prepare snippet with Postgres commands for root user'
      ansible.builtin.template:
        src: 'postgresql_snippet.txt.j2'
        dest: '/root/postgresql_snippet.txt'
        owner: 'root'
        group: 'root'
        mode: '0644'
