---
- name: 'Gather facts'
  hosts: 'all'
  gather_facts: true
  become: true

- name: 'Postgresql snippet'
  hosts: 'postgresql-client'
  gather_facts: true
  become: true

  tasks:

    - name: 'Prepare snippet with Postgres commands for vagrant user'
      ansible.builtin.template:
        src: 'postgresql_snippet.txt.j2'
        dest: '/home/vagrant/postgresql_snippet.txt'
        owner: 'vagrant'
        group: 'vagrant'
        mode: '0644'

    - name: 'Prepare snippet with Postgres commands for root user'
      ansible.builtin.template:
        src: 'postgresql_snippet.txt.j2'
        dest: '/root/postgresql_snippet.txt'
        owner: 'root'
        group: 'root'
        mode: '0644'

    - name: 'Output psql command for example-user'
      ansible.builtin.debug:
        msg: "Connection (from postgresql-client) as the example-user will be successful: psql -h {{ hostvars['postgresql-server']['ansible_default_ipv4']['address'] }} -d example-database -U example-user"

    - name: 'Output example-user credentials'
      ansible.builtin.debug:
        msg: "The password for the example-user is 'anothertotallysecurepassword'"

    - name: 'Output psql command for root user (that will fail)'
      ansible.builtin.debug:
        msg: "Connection (from postgresql-client) as the root user will fail: psql -h {{ hostvars['postgresql-server']['ansible_default_ipv4']['address'] }} -d example-database -U postgres"
